### ISSUE TITLE
Can't open FIT file

### ISSUE THREAD

**Issue by noeldum** [dtcooper/python-fitparse#29]
Is that project still alive?
I tried this below on a file from a forerunner

```
from fitparse import FitFile
fitfile = FitFile("76NE5832.FIT")
```

That result as

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 38, in __init__
    self._parse_file_header()
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 123, in _parse_file_header
    self._read_and_assert_crc(allow_zero=True)
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 83, in _read_and_assert_crc
    crc_expected, crc_actual = self._crc, self._read_struct('H')
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 75, in _read_struct
    raise FitEOFError("Tried to read %d bytes from .FIT file but got %d" % (size, len(data)))
fitparse.utils.FitEOFError: Tried to read 2 bytes from .FIT file but got 0
```

**Comment by pR0Ps** [comment]
Please provide a sample file or there's not much we can do.

**Comment by noeldum** [comment]
Sure. Here is the file.
[76NE5832.FIT.zip](https://github.com/dtcooper/python-fitparse/files/1100406/76NE5832.FIT.zip)

**Comment by pR0Ps** [comment]
I just tried parsing that file using the version at 5283af577d593bfb11bdc582c7d2df61b6ce3c40 and it worked fine. Are you using the latest version?

@dtcooper Maybe the PyPI version needs updating?

**Comment by noeldum** [comment]
Thank you. I updated to the 5283af5 version but can't confirm version was the actual problem here.

Found fitdump to work and not my initial code indicated above.

Solved the issue by feeding the full path. (although script and data file being in the same directory).
fitfile = FitFile("./76NE5832.FIT")
instead of
fitfile = FitFile("76NE5832.FIT")

**Comment by pR0Ps** [comment]
Oh wow, so this is definitely a bug and a really unexpected one at that. It's due to a combination of Python2's poor bytes/str behaviour, and the *length* and *extension* of the filename if you can believe that.

The check for "did you proivde raw file data to the constructor" is currently this:
```python
isinstance(fileish, bytes) and fileish[8:12] == b'.FIT':
```
In Python 2, the passed in string is of type `bytes` and of course `76NE5832.FIT[8:12]` == `.FIT` so this returns True and assumes the filename is the raw bytes of the file. Of course, this breaks when it tries to read the header block from it.

I'll have a fix soon.
