### ISSUE TITLE
max_speed && speed problem 

### ISSUE THREAD

**Issue by beyoung** [dtcooper/python-fitparse#84]
fit file:
[2019-2-13-10-36-52-12791.fit.zip](https://github.com/dtcooper/python-fitparse/files/2913492/2019-2-13-10-36-52-12791.fit.zip)

fitparse version 1.0.1
max_speed : 14.201

fitparse version 1.1.0
max_speed: 14201

and speed encounter the same problem.

**Comment by beyoung** [comment]
As I dive into detail, I found that bug is caused by generate_profile.py script, in line [468](https://github.com/dtcooper/python-fitparse/blob/master/scripts/generate_profile.py#L469), which wipe out scale, offset and units.
But I think that only in situation of components scale is None or b'' or is not digit( 
    ![image](https://user-images.githubusercontent.com/2298389/53784353-f06aad00-3f4f-11e9-92b2-b5a2471e051e.png)
 ), we can wipe out scale, offset and units. so, wipe code should be 
![image](https://user-images.githubusercontent.com/2298389/53784249-9ff34f80-3f4f-11e9-9ace-627a89064548.png).  If you agree with me, I'd make a PR.

**Comment by cberthiaume** [comment]
Hi, we've been happy users of this library for a while. We recently encountered an issue that is resolved by [this](https://github.com/dtcooper/python-fitparse/blob/master/fitparse/records.py#L390) work around which is available in 1.1. However, the bug described in this issue is preventing us from moving to 1.1. Any idea when this change will make it to a release that we can install with pip?

Thanks a lot for all the work on this library.

**Comment by beyoung** [comment]
@cberthiaume You can create a new issue to detail your problem.

**Comment by cberthiaume** [comment]
I'm confused, the issue in this issue is my problem. I see it's been merged. I'd just like to know when it will be released.

**Comment by dtcooper** [comment]
@cberthiaume, you're able to install it from pip immediately. Just use the latest SHA, see [this post on Stack Overflow](https://stackoverflow.com/a/13754517).

**Comment by cberthiaume** [comment]
Excellent, thanks @dtcooper!
